#!/bin/sh
# based on spark https://github.com/holman/spark
# bash-specific bits squeezed by willee

# The MIT License
# 
# Copyright (c) Zach Holman, http://zachholman.com
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

spark() {
    local step numbers min max
    min=1000000000; max=0; ticks=". ▁ ▂ ▃ ▄ ▅ ▆ ▇ █ █"

    for n in ${@}; do
        n=${n%.*}
        [ ${n} -lt ${min} ] && min=${n}
        [ ${n} -gt ${max} ] && max=${n}
        numbers=${numbers}${numbers:+ }${n}
    done

    step=$(( (( ${max} - ${min} ) << 8 ) / 9 ))
    [ "${step}" -lt 1 ] && step=1

    aux_get_tick() { eval printf \"\%s\" \$$(( $1 + 2 )); }
    
    for n in ${numbers}; do
        aux_get_tick $(( ((${n}-${min})<<8)/${step} )) ${ticks}
    done
    echo
}

spark ${@:-`cat`}

